
POST http://localhost:9000/api/commerce HTTP/1.1
Content-Type: application/json

{
    "commerceName" : "sabado",
    "cif" : "00409442T",
    "adress" : "Primorosky ",
    "email" : "sabado@gmail.com",
    "phone" :  "678765453"

}

###

GET http://localhost:9000/api/commerce?sort=true HTTP/1.1

###

GET http://localhost:9000/api/commerce?sort=false HTTP/1.1
###
GET http://localhost:9000/api/commerce/02730413Z HTTP/1.1

###

PUT http://localhost:9000/api/commerce/02730413Z HTTP/1.1
Content-Type: application/json

{
    "commerceName" : "MacDonald",
    "adress" : "C/viernes n 7",
    "email" : "macdonal@gmail.com",
    "phone" :  "678765453"

}

###

DELETE http://localhost:9000/api/commerce/07409442T?soft=false


###